spring:
  application:
    name: apace-user-service
server: 
  port: 8080
  
eureka:
  client: 
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
#      http://localhost:8761/eureka
  instance:
    preferIpAddress: true