spring:
  profiles:
    active: default
  application:
    name: apace-edge-server
    
server:
  port: 9090

eureka:
  client: 
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
#     defaultZone:http://localhost:8761/eureka
    instance:
      preferIpAddress: true

#https://github.com/spring-cloud/spring-cloud-netflix/issues/853
zuul:
#  ignoredServices: '*'
  routes:
    apace-user-service:
      path: /api/user/**
#     url: http://localhost:8080/api/user/
      serviceId: apace-user-service
      stripPrefix: false
#     sensitiveHeaders: Authorization

#ribbon: 
#  ConnectTimeout: 30000
#  ReadTimeout: 990000
#  maxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  eureka:
#    enabled: true

      
management:
  security: 
    enabled: false 
  endpoints:
    web: 
      exposure: 
        include: health, info, metrics, routes
  endpoint:
    info:
      enabled: true
      management: 
    health:
      show-details: "ALWAYS"
    routes:
      enabled: true
    filters:
      enabled: true
      
---
      
# settings only applicable as per profile

spring:
  profiles: qa, prod
  
  
---

# settings only applicable as per profile

spring:
  profiles: prod
   
