spring:
  application:
    name: apace-discovery-server
server:
  port: 8761
 
eureka: 
   instance: 
     preferIpAddress : true
#     hostname: localhost
   client: 
     registerWithEureka: true
     fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   server:
     enableSelfPreservation: true
#    waitTimeInMsWhenSyncEmpty: 0